### PR TITLE
Upgrade to Stack package set LTS 20.5

### PR DESCRIPTION
**Pull request by ad-si**

### CODE REVIEW

**Comment by ad-si** [comment]
🛎️ Ping 😉

**Review by albertov — APPROVED** [review]
Thanks! Sorry for the delay

**Comment by ad-si** [comment]
👍, but approving it is not enough. Someone also has to merge it. 😅

**Comment by albertov** [comment]
Cc @rapto can you merge this please?

**Comment by ad-si** [comment]
Actually, let me update this PR first! The version in the PR is old by now as well 😅

**Comment by ad-si** [comment]
Ok, I think it's ready to merge @rapto!
(You should probably squash the 2 commits …)

**Comment by rapto** [comment]
I am merging this, but I no longer have time to dedicate to this project. Cheers.

**Comment by ad-si** [comment]
Thanks! Understandable, I'd be happy to help out, since I use it in a few of my projects.

You'd have to add me as a maintainer at https://hackage.haskell.org/package/iso8601-duration/maintainers/, so I can publish new releases.

**Comment by albertov** [comment]
> Thanks! Understandable, I'd be happy to help out, since I use it in a few of my projects.
> 
> You'd have to add me as a maintainer at https://hackage.haskell.org/package/iso8601-duration/maintainers/, so I can publish new releases.

@ad-si I can add you as a maintainer, what's your username at Hackage?

**Comment by albertov** [comment]
@rapto Perhaps you can configure this repo as moved to albertov/iso8601-duration where I can merge stuff?

**Comment by albertov** [comment]
I just pushed the new version to https://hackage.haskell.org/package/iso8601-duration-0.1.2.0

**Comment by ad-si** [comment]
Great 👍
=> https://hackage.haskell.org/user/adrian

**Comment by albertov** [comment]
> Great 👍 => https://hackage.haskell.org/user/adrian

@ad-si you're a maintainer now https://hackage.haskell.org/package/iso8601-duration/maintainers/

**Pull request merged**
